services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "Release"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:e59ba8783bf7bc02a4779f103bb0d8751ac0e10f9471089709608377eded7aa8
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 20s
            retries: 10
        
    cache:
        image: "redis:7-alpine@sha256:0bc09d9f486508aa42ecc2f18012bb1e3a1b2744ef3a6ad30942fa12579f0b03"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        restart: unless-stopped

volumes: 
    cache:
    database:
