version: "3.9"
services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.Development.json:/app/appsettings.Development.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:c222be005ac3f8183dd3c7d1930aebbc4cd8d05d42ba92578174b7a77123efa8
        env_file:
            - .env
        ports:
            - "3306:3306"
        restart: unless-stopped
        healthcheck:
            test: 'mariadb-admin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 30s
            retries: 10
            start_period: 10s
        
    cache:
        image: "redis:7-alpine@sha256:3ce533b2b057f74b235d1d8697ae08b1b6ff0a5e16827ea6a377b6365693c7ed"
        ports:
            - "6379:6379"
        restart: unless-stopped
        healthcheck:
            test: '[ $(redis-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s
