version: "3.9"
services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "Release"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:f0a6faee9d0e55492f238d1d11ff13d77616ea12d8c38bedf090da2ee05532be
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 20s
            retries: 10
        
    cache:
        image: "redis:7-alpine@sha256:6abca08e3a4d1c5fb834782b642324402b5fbd79a4bc00880bfce693ad98b651"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        restart: unless-stopped

volumes: 
    cache:
    database:
