version: "3.9"
services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.Development.json:/app/appsettings.Development.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:b5e508abc5d889425e90212541e30d29279b7ed34dd74bab5bb715b2f2aeeb7b
        env_file:
            - .env
        ports:
            - "3306:3306"
        restart: unless-stopped
        healthcheck:
            test: 'mariadb-admin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 30s
            retries: 10
            start_period: 10s
        
    cache:
        image: "redis:7-alpine@sha256:641c365890fc79f182fb198c80ee807d040b9cfdb19cceb7f10c55a268d212b8"
        ports:
            - "6379:6379"
        restart: unless-stopped
        healthcheck:
            test: '[ $(redis-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s
