name: 'Production Continuous Deployment'

on:
  release:
    types: [released]

jobs:
  package:
    name: 'Publish Container'
    runs-on: ubuntu-latest
    steps:
      # Setup working environment for Docker
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - id: docker_meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e # v5
        with:
          images: ghcr.io/sn0wcrack/saucybot-discord
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
      - name: 'Login to Container Registry'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: 'Build and Publish'
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          CONFIGURATION: Release
        with:
          push: true
          context: ./SaucyBot
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CONFIGURATION=Release
          
  deploy:
    name: 'Deploy'
    needs: package
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: appleboy/ssh-action@8f949198563a347a01c65ffc60399aef2b59d4ab # v1.0.1
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./update.sh
