name: 'Continuous Integration'

on:
  workflow_dispatch:
  push:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['7.x', '8.x']

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
