name: 'Continuous Integration'

on:
  workflow_dispatch:
  push:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.x']

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
